# Generated by Django 5.0 on 2023-12-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(default=False, unique=True, verbose_name='ID в телеграмме')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price_limit', models.CharField(max_length=200, verbose_name='Стоимость')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата розыгрыша')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на розыгрыш')),
                ('players_distributed', models.BooleanField(verbose_name='Распределено')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='santa_bot.organizer', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, default=False, unique=True, verbose_name='ID в телеграмме')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('wishlist', models.TextField(blank=True, null=True, verbose_name='Подарки')),
                ('avoided_players', models.ManyToManyField(blank=True, to='santa_bot.player', verbose_name='Не дружат')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='santa_bot.game', verbose_name='Розыгрыш')),
                ('giftee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giftee_players', to='santa_bot.player', verbose_name='Кому дарит')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
