# Generated by Django 5.0 on 2023-12-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useravoidance',
            options={'verbose_name': 'НЕ дружат', 'verbose_name_plural': 'НЕ дружат'},
        ),
        migrations.AlterField(
            model_name='useravoidance',
            name='avoided_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoided_user', to='santa_bot.user', verbose_name='Пользователь 2'),
        ),
        migrations.AlterField(
            model_name='useravoidance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoided_user', to='santa_bot.game', verbose_name='Розыгрыш'),
        ),
        migrations.AlterField(
            model_name='useravoidance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoiding_user', to='santa_bot.user', verbose_name='Пользователь 1'),
        ),
        migrations.CreateModel(
            name='ResultGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultgame', to='santa_bot.game', verbose_name='Розыгрыш')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='santa_bot.user', verbose_name='Даритель')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='santa_bot.user', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
