# Generated by Django 5.0 on 2023-12-16 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки подарков'),
        ),
        migrations.AlterField(
            model_name='player',
            name='giftee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santa', to='santa_bot.player', verbose_name='Кому дарит'),
        ),
    ]
