# Generated by Django 5.0 on 2023-12-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0002_alter_game_send_date_alter_player_giftee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterField(
            model_name='game',
            name='players_distributed',
            field=models.BooleanField(verbose_name='Распределено?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avoided_players',
            field=models.ManyToManyField(blank=True, to='santa_bot.player', verbose_name='избегаемые игроки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(default='lolkek@example.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='santa_bot.game', verbose_name='Розыгрыш'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='John', max_length=50, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.IntegerField(verbose_name='telegram ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wishlist',
            field=models.TextField(blank=True, null=True, verbose_name='подарки'),
        ),
    ]
