# Generated by Django 5.0 on 2023-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_bot', '0003_alter_player_options_alter_game_players_distributed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='ID в телеграмме'),
        ),
    ]
